# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher
$webBrowser = firefox

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod+SHIFT, Return, exec, $webBrowser
bind = $mainMod, D, exec, wofi --show drun

input {
    kb_layout = br
    kb_model = abnt2
    
    # Keep your other existing input settings below
    follow_mouse = 1
}

exec-once = hyprpaper
exec-once = waybar

source = ~/.config/hypr/monitors.conf
